# .github/workflows/update_readme_feed.yml
name: Update README with Latest Blog Post

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # Use a Personal Access Token (PAT) for more reliable checkouts if needed,
        # but the GITHUB_TOKEN should work with the permissions block.
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install feedparser

      - name: Run Python script to update README
        run: python ./scripts/update_readme.py

      - name: Commit and push changes
        run: |
          # Configure git with the action's identity
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add the changed file
          git add README.md
          
          # Check if there are changes to commit
          if ! git diff-index --quiet HEAD; then
            # Commit the changes
            git commit -m "chore: Update latest Android blog post"

            git pull --rebase --autostash
          
            # Push the updated branch
            git push
          else
            echo "No changes to commit."
          fi